window.SimulatedData = {

  workerProgressReport: {
    A: {
      workerName: 'Madeleine Willson',
      claimNo: '20042047',
      appId: '712041',
      submitted: 'March 19, 2024 19:21',
      returnToWork: { status: 'returnedOn', returnDate: 'March 15, 2024' },
      workType: { key: 'modifiedReduced' },
      returnGoingComment: 'Terrible. Testing Testing',
      expectedReturnDate: '',
      returnConcerns: '',
      recentContact: { name: '', date: '' },
      recovery: { status: 'recovered', comments: '' },
      pain: 2,
      medicalTreatment: {
        status: 'not',
        providerType: '',
        last: { date: '', name: '' },
        next: { date: '', name: '' },
        frequency: '',
      },
      medication: { status: 'not', name: '' },
      homeExercises: { status: 'not', list: '' },
      otherInfo: 'No info Testing Testing',
    },
    B: {
      workerName: 'Arjun Mehta',
      claimNo: '20118834',
      appId: '905522',
      submitted: 'July 22, 2026 11:04',
      returnToWork: { status: 'notReturned' },
      workType: { key: 'other', otherText: 'Not applicable — off work' },
      returnGoingComment: 'I have not attempted a return yet; my physiotherapist wants another two weeks of rest before any modified duties are considered.',
      expectedReturnDate: 'August 11, 2026',
      returnConcerns: 'My workstation requires repetitive lifting above shoulder height, which my treating physician has flagged as a direct aggravating factor for my shoulder injury. I would need a modified station or a temporary reassignment before I can safely return, and I am concerned my employer has not yet confirmed either option is available.',
      recentContact: { name: 'Priya Nair, HR Coordinator', date: 'July 18, 2026' },
      recovery: { status: 'notRecovered', comments: 'Still experiencing significant stiffness in the morning and sharp pain when reaching overhead. Range of motion has improved roughly 30% since my last report but I am far from full function.' },
      pain: 6,
      medicalTreatment: {
        status: 'continuing',
        providerType: 'Physiotherapist',
        last: { date: 'July 21, 2026', name: 'Dr. S. Okafor, Riverbend Physiotherapy' },
        next: { date: 'July 29, 2026', name: 'Dr. S. Okafor, Riverbend Physiotherapy' },
        frequency: 'Twice weekly',
      },
      medication: { status: 'taking', name: 'Naproxen 250mg, as needed for pain' },
      homeExercises: { status: 'doing', list: 'Pendulum swings, resistance band external rotations, wall crawls, and scapular squeezes — three sets of 15 reps, twice daily as prescribed by my physiotherapist.' },
      otherInfo: 'I would also like to flag that I have an upcoming MRI scheduled for August 4, 2026 to rule out a partial rotator cuff tear, and will submit those results as soon as they are available. My employer has been supportive throughout this process and I wanted that noted on file.',
    },
  },

  medicalTravelExpense: {

    A: {
      workerName: 'Madeleine Willson',
      claimNo: '20042047',
      appId: '712041',
      submitted: 'March 19, 2024 19:21',
      address: '48 Sherbrook St, Winnipeg, MB',
      phone: '(204) 555-0134',
      payment: { method: 'directDeposit' },
      expenseRows: [
        ['Mar 4, 2024', 'Physiotherapy appointment', 'Home', 'Riverbend Physio', '6', '4.20'],
        ['Mar 11, 2024', 'Physiotherapy appointment', 'Home', 'Riverbend Physio', '6', '4.20'],
      ],
      totalAmount: '$8.40',
    },

    B: {
      workerName: 'Arjun Mehta',
      claimNo: '20118834',
      appId: '905522',
      submitted: 'July 22, 2026 11:04',
      address: '212 Corydon Ave, Winnipeg, MB',
      phone: '(204) 555-0198',
      payment: { method: 'cheque' },
      expenseRows: [
        ['Jun 30, 2026', 'Physiotherapy appointment', 'Home', 'Riverbend Physiotherapy', '9', '6.30'],
        ['Jul 2, 2026', 'Physiotherapy appointment', 'Home', 'Riverbend Physiotherapy', '9', '6.30'],
        ['Jul 4, 2026', 'Specialist consultation', 'Home', 'Grace Hospital Orthopedics', '14', '9.80'],
        ['Jul 7, 2026', 'Physiotherapy appointment', 'Home', 'Riverbend Physiotherapy', '9', '6.30'],
        ['Jul 9, 2026', 'Physiotherapy appointment', 'Home', 'Riverbend Physiotherapy', '9', '6.30'],
        ['Jul 11, 2026', 'X-ray imaging', 'Home', 'Grace Hospital Imaging', '14', '9.80'],
        ['Jul 14, 2026', 'Physiotherapy appointment', 'Home', 'Riverbend Physiotherapy', '9', '6.30'],
        ['Jul 16, 2026', 'Physiotherapy appointment', 'Home', 'Riverbend Physiotherapy', '9', '6.30'],
        ['Jul 18, 2026', 'Pharmacy pick-up', 'Home', 'Corydon Pharmacy', '2', '1.40'],
        ['Jul 21, 2026', 'Physiotherapy appointment', 'Home', 'Riverbend Physiotherapy', '9', '6.30'],
        ['Jul 23, 2026', 'MRI imaging', 'Home', 'Grace Hospital Imaging', '14', '9.80'],
        ['Jul 25, 2026', 'Physiotherapy appointment', 'Home', 'Riverbend Physiotherapy', '9', '6.30'],
      ],
      totalAmount: '$85.20',
    },
  },
};
